server:
  port: 8080
  servlet:
    context-path: /ycx
  tomcat:
    uri-encoding: utf-8

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: memor
  datasource:
    url: jdbc:mysql://localhost:3306/memor
    username: root
    password: 0313..Ycx
    type: com.alibaba.druid.pool.DruidDataSource